name: OrderService CI/CD workflow

on:
  push:
    branches: [ "integration" ]
  pull_request:
    branches: [ "*" ]
    paths: [ '**/*']

jobs:
  build:

    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:14
        ports:
          - 5432:5432
        env:
          POSTGRES_DB: test_database
          POSTGRES_USER: test_user
          POSTGRES_PASSWORD: test_password
        options: >-
          --health-cmd="pg_isready -U test_user -d test_database"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=5

    steps:
    # Step1: Checkout the code
    - uses: actions/checkout@v4

    #Step2: Setup JDK 17
    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven

     # Step3: Wait for PostgreSQL to be ready
    - name: Wait for PostgreSQL
      run: |
        until pg_isready -h localhost -p 5432 -U test_user -d test_database; do
          echo "Waiting for PostgreSQL..."
          sleep 5
        done

    #Step 4: Build the project with Maven
    - name: Build with Maven
      run: mvn -B package --file pom.xml

    # Step 5: Run Unit Tests
    - name: Run Unit Tests
      run: mvn -B test --file pom.xml
      
    - name: Generate Code Coverage
      run: mvn jacoco:report --file pom.xml
      
    # Step 6: Run Integration Tests
    - name: Run Integration Tests
      run: mvn -B verify --file pom.xml

      # Optional: Uploads the full dependency graph to GitHub to improve the quality of Dependabot alerts this repository can receive
    - name: Update dependency graph
      run: mvn com.github.ferstl:depgraph-maven-plugin:4.0.1:graph --file pom.xml
